name: Update README
on:
    schedule:
        - cron: '0 12 5 * *'

jobs:
    update-readme:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codigo
              uses: actions/checkout@v2

            - name: Actualizar README
              run: |
                echo "## Actualidaciones" >> README.md
                echo "Fecha de última actualizacion: $(date + '%Y-%m-%d %H:%M:%S')" >> README.md
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git commit -m "Actualizacion automatica del README" -a
                git push
